### ISSUE TITLE
[METRICBEAT] - Add a way to set index.number_of_replicas when monitor stack

### ISSUE THREAD

**Issue by disaster37** [webcenter-fr/elasticsearch-operator#137]
In many case, the Elasticsearch cluster dedicated to minotor Elasticsearch have only one node.
So, the metricbeat must be set the `number_of_replicas` to `0` when it create the index template.

**Comment by disaster37** [comment]
Add a way to inject
```yaml
config:
    'metricbeat.yml': |-
      setup.template.settings:
        index.number_of_replicas: 0
```
